import { Product } from "../types/product.types";

export const dummyProducts: Product[] = [
  {
    id: 1,
    name: "Bluetooth Headset",
    category: "Electronics",
    price: 25,
    quantity: 5,
    isDisabled: false,
  },
  {
    id: 2,
    name: "Edifier M34560 Speaker",
    category: "Electronics",
    price: 35,
    quantity: 0,
    isDisabled: false,
  },
  {
    id: 3,
    name: "Sony 4K 55-inch Ultra TV",
    category: "Electronics",
    price: 800,
    quantity: 2,
    isDisabled: false,
  },
  {
    id: 4,
    name: "Samsung 55-inch TV",
    category: "Electronics",
    price: 500,
    quantity: 10,
    isDisabled: false,
  },
  {
    id: 5,
    name: "Samsung S24 Ultra",
    category: "Phones",
    price: 1200,
    quantity: 3,
    isDisabled: false,
  },
  {
    id: 6,
    name: "Apple iPhone 14 Pro",
    category: "Phones",
    price: 1500,
    quantity: 0,
    isDisabled: true,
  },
  {
    id: 7,
    name: "Logitech MX Master 3",
    category: "Accessories",
    price: 100,
    quantity: 20,
    isDisabled: false,
  },
  {
    id: 8,
    name: "Dell XPS 13 Laptop",
    category: "Laptops",
    price: 1200,
    quantity: 5,
    isDisabled: false,
  },
  {
    id: 9,
    name: "Apple MacBook Pro 16",
    category: "Laptops",
    price: 2500,
    quantity: 2,
    isDisabled: false,
  },
  {
    id: 10,
    name: "Sony Noise Cancelling Headphones",
    category: "Accessories",
    price: 300,
    quantity: 15,
    isDisabled: false,
  },
];
